In [1]:
import json
import pandas as pd

In [ ]:
with open('results/GEVAL_solar_vl2.json') as f:
    persona_solar = json.load(f)

In [2]:
persona_solar = pd.DataFrame.from_dict(data=persona_solar, orient='columns')
persona_solar.describe()

       coherence  engagingness  naturalness  groundedness
count  54.000000     54.000000    54.000000     54.000000
mean    4.351852      3.333333     4.348148      3.633333
std     1.112153      0.937681     0.986272      1.198899
min     1.000000      1.000000     1.000000      1.000000
25%     4.425000      3.025000     4.250000      2.925000
50%     4.900000      3.600000     4.800000      3.900000
75%     5.000000      3.900000     4.900000      4.700000
max     5.000000      4.900000     5.000000      5.000000

In [4]:
with open('results/GEVAL_solar_vl2_no_persona.json') as f:
    no_persona_solar = json.load(f)

In [5]:
no_persona_solar = pd.DataFrame.from_dict(data=no_persona_solar, orient='columns')
no_persona_solar.describe()

       coherence  engagingness  naturalness  groundedness
count  54.000000     54.000000    54.000000     54.000000
mean    4.124074      3.194444     4.005556      3.461111
std     1.351161      0.967669     1.235851      1.449322
min     1.000000      1.000000     1.000000      1.000000
25%     3.975000      2.850000     3.800000      2.275000
50%     4.900000      3.500000     4.450000      3.950000
75%     5.000000      3.775000     4.900000      4.700000
max     5.000000      4.700000     5.000000      5.000000